baseURL = 'https://my-sheet-music.netlify.app/'
languageCode = 'en-us'
title = 'Quint'
theme = "quint"
summaryLength = 20                  # Number of characters in your card summaries

[params]
useToc = true
description = 'Sheet music site for the Hugo theme Quint.'

[[menus.main]]
name = 'GitHub'
url = 'https://github.com/ramandrosoa/'

[markup.goldmark.renderer]
    unsafe = true


